--
-- PostgreSQL database dump
--

-- Dumped from database version 9.5.0.5
-- Dumped by pg_dump version 9.5.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

SET search_path = i2b2metadata, pg_catalog;


INSERT INTO pcornet_enroll VALUES (1, '\PCORI\ENROLLMENT\', 'Enrollment', 'N', 'CA ', NULL, NULL, NULL, 'concept_cd', 'CONCEPT_DIMENSION', 'concept_path', 'T', 'like', '\PCORI\ENROLLMENT\', NULL, 'Enrollment', '@', '2001-01-01 00:00:00', '2001-01-01 00:00:00', '2001-01-01 00:00:00', 'PCORNET_CDM', NULL, NULL, '\PCORI\', 'ENROLLMENT', NULL);
INSERT INTO pcornet_enroll VALUES (2, '\PCORI_MOD\CHART\Y\', 'Yes', 'N', 'RA ', NULL, 'CHART:Y', NULL, 'PATIENT_NUM', 'OBSERVATION_FACT', '1', 'N', '=', '1', NULL, 'Yes', '\PCORI\ENROLLMENT\ENR_BASIS\%', '2001-01-01 00:00:00', '2001-01-01 00:00:00', '2001-01-01 00:00:00', 'PCORNET_CDM', NULL, NULL, '\PCORI_MOD\CHART\', 'Y', 'CHART:Y');
INSERT INTO pcornet_enroll VALUES (1, '\PCORI_MOD\CHART\', 'Chart', 'N', 'OA ', NULL, NULL, NULL, 'modifier_cd', 'MODIFIER_DIMENSION', 'modifier_path', 'T', 'like', '\PCORI_MOD\CHART\', NULL, 'Chart abstraction flag to answer the question, Are you able to request charts for this member? This flag does not address chart availability. Mark as Y if there are no contractual restrictions between you and the member (or sponsor) that would prohibit you from requesting any chart for this member.', '\PCORI\ENROLLMENT\ENR_BASIS\%', '2001-01-01 00:00:00', '2001-01-01 00:00:00', '2001-01-01 00:00:00', 'PCORNET_CDM', NULL, NULL, '\PCORI_MOD\', 'CHART', NULL);
INSERT INTO pcornet_enroll VALUES (2, '\PCORI\ENROLLMENT\ENR_START_DATE\', 'ENR_START_DATE', 'N', 'LH ', NULL, 'ENROLLMENT:ENR_START_DATE', '<?xml version="1.0" encoding="UTF-8"?>        <ValueMetadata>          <Version>3.2</Version>          <CreationDateTime>01/26/2011 00:00:00</CreationDateTime>          <DataType>String</DataType>          <Oktousevalues>Y</Oktousevalues>          <UnitValues>            <NormalUnits>DATE</NormalUnits>          </UnitValues>        </ValueMetadata>', 'concept_cd', 'CONCEPT_DIMENSION', 'concept_path', 'D', 'like', '\PCORI\ENROLLMENT\ENR_START_DATE\', 'Added scheme to baasecode:ENR_START_DATE:', 'Date of the beginning of the enrollment period. If the exact date is unknown, use the first day of the month.For implementation of the CDM, a long span of longitudinal data is desirable; however, especially for historical data more than a decade old, the appropriate beginning date should be determined by the partner''s knowledge of the validity and usability of the data. More specific guidance can be provided through implementation discussions.', '@', '2014-06-05 00:00:00', '2014-06-05 00:00:00', '2014-06-05 00:00:00', 'PCORNET_CDM', NULL, NULL, '\PCORI\ENROLLMENT\', 'ENR_START_DATE', 'ENROLLMENT:ENR_START_DATE');
INSERT INTO pcornet_enroll VALUES (2, '\PCORI_MOD\CHART\OT\', 'Other', 'N', 'RA ', NULL, 'CHART:OT', NULL, 'PATIENT_NUM', 'MODIFIER_DIMENSION', '1', 'N', '=', '0', NULL, 'Other: A data field is present in the source system, but the source value cannot be mapped to the CDM.', '\PCORI\ENROLLMENT\ENR_BASIS\%', '2014-06-02 19:44:16', '2014-06-02 19:44:16', '2014-06-02 19:44:16', 'PCORNET_CDM', NULL, NULL, '\PCORI_MOD\CHART\', 'OT', 'CHART:OT');
INSERT INTO pcornet_enroll VALUES (2, '\PCORI\ENROLLMENT\ENR_BASIS\', 'Enrolled', 'N', 'CA ', NULL, 'ENROLLMENT:ENROLLED', NULL, 'PATIENT_NUM', 'CONCEPT_DIMENSION', 'concept_path', 'T', 'like', '\PCORI\ENROLLMENT\ENR_BASIS\', 'Added scheme to baasecode:ENROLLED', 'Populate the date of the beginning and end of the enrollment period. If the exact date is unknown for the start date, use the first day of the month. If the exact date is unknown for the end date, use the last day of the month. For implementation of the CDM, a long span of longitudinal data is desirable; however, especially for historical data more than a decade old, the appropriate beginning date should be determined by the data partner''s knowledge of the validity and usability of the data. More specific guidance can be provided through implementation discussions.', '@', '2001-01-01 00:00:00', '2001-01-01 00:00:00', '2001-01-01 00:00:00', 'PCORNET_CDM', NULL, NULL, '\PCORI\ENROLLMENT\', 'ENR_BASIS', 'ENROLLMENT:ENROLLED');
INSERT INTO pcornet_enroll VALUES (2, '\PCORI_MOD\CHART\N\', 'No', 'N', 'RA ', NULL, 'CHART:N', NULL, 'PATIENT_NUM', 'VISIT_DIMENSION', '1', 'N', '=', '0', NULL, 'No', '\PCORI\ENROLLMENT\ENR_BASIS\%', '2001-01-01 00:00:00', '2001-01-01 00:00:00', '2001-01-01 00:00:00', 'PCORNET_CDM', NULL, NULL, '\PCORI_MOD\CHART\', 'N', 'CHART:N');
INSERT INTO pcornet_enroll VALUES (2, '\PCORI\ENROLLMENT\ENR_END_DATE\', 'ENR_END_DATE', 'N', 'LH ', NULL, 'ENROLLMENT:ENR_END_DATE', '<?xml version="1.0" encoding="UTF-8"?>        <ValueMetadata>          <Version>3.2</Version>          <CreationDateTime>01/26/2011 00:00:00</CreationDateTime>          <DataType>String</DataType>          <Oktousevalues>Y</Oktousevalues>          <UnitValues>            <NormalUnits>DATE</NormalUnits>          </UnitValues>        </ValueMetadata>', 'concept_cd', 'CONCEPT_DIMENSION', 'concept_path', 'D', 'like', '\PCORI\ENROLLMENT\ENR_END_DATE\', 'Added scheme to baasecode:ENR_END_DATE:', 'Date of the end of the enrollment period. If the exact date is unknown, use the last day of the month.', '@', '2014-06-05 00:00:00', '2014-06-05 00:00:00', '2014-06-05 00:00:00', 'PCORNET_CDM', NULL, NULL, '\PCORI\ENROLLMENT\', 'ENR_END_DATE', 'ENROLLMENT:ENR_END_DATE');
INSERT INTO pcornet_enroll VALUES (2, '\PCORI_MOD\CHART\NI\', 'No information', 'N', 'RA ', NULL, 'CHART:NI', NULL, 'PATIENT_NUM', 'VISIT_DIMENSION', '1', 'N', '=', '0', NULL, 'No information: A data field is present in the source system, but the source value is null or blank. Note: presently returns the same values as its parent fact.', '\PCORI\ENROLLMENT\ENR_BASIS\%', '2014-06-02 19:40:30', '2014-06-02 19:40:30', '2014-06-02 19:40:30', 'PCORNET_CDM', NULL, NULL, '\PCORI_MOD\CHART\', 'NI', 'CHART:NI');
INSERT INTO pcornet_enroll VALUES (1, '\PCORI_MOD\CHART\', 'Chart', 'N', 'OA ', NULL, NULL, NULL, 'modifier_cd', 'MODIFIER_DIMENSION', 'modifier_path', 'T', 'like', '\PCORI_MOD\CHART\', NULL, 'Chart abstraction flag to answer the question, Are you able to request charts for this member? This flag does not address chart availability. Mark as Y if there are no contractual restrictions between you and the member (or sponsor) that would prohibit you from requesting any chart for this member.', '\PCORI\ENROLLMENT\ENR_BASIS\', '2001-01-01 00:00:00', '2001-01-01 00:00:00', '2001-01-01 00:00:00', 'PCORNET_CDM', NULL, 'Y', '\PCORI_MOD\', 'CHART', NULL);
INSERT INTO pcornet_enroll VALUES (3, '\PCORI\ENROLLMENT\ENR_BASIS\I\', 'Insurance', 'N', 'LI ', NULL, 'ENR_BASIS:I', NULL, 'PATIENT_NUM', 'OBSERVATION_FACT', '1', 'T', '=', '0', NULL, 'Insurance: The start and stop dates are based upon the concept of enrollment with health plan insurance', '@', '2001-01-01 00:00:00', '2001-01-01 00:00:00', '2001-01-01 00:00:00', 'PCORNET_CDM', NULL, NULL, '\PCORI\ENROLLMENT\ENR_BASIS\', 'I', 'ENR_BASIS:I');
INSERT INTO pcornet_enroll VALUES (2, '\PCORI_MOD\CHART\UN\', 'Unknown', 'N', 'RA ', NULL, 'CHART:UN', NULL, 'PATIENT_NUM', 'MODIFIER_DIMENSION', '1', 'N', '=', '0', NULL, 'Unknown: A data field is present in the source system, but the source value explicitly denotes an unknown value.', '\PCORI\ENROLLMENT\ENR_BASIS\%', '2014-06-02 19:43:08', '2014-06-02 19:43:08', '2014-06-02 19:43:08', 'PCORNET_CDM', NULL, NULL, '\PCORI_MOD\CHART\', 'UN', 'CHART:UN');
INSERT INTO pcornet_enroll VALUES (3, '\PCORI\ENROLLMENT\ENR_BASIS\G\', 'Geography', 'N', 'LI ', NULL, 'ENR_BASIS:G', NULL, 'PATIENT_NUM', 'OBSERVATION_FACT', 'concept_cd', 'T', 'LIKE', '\PCORI\ENROLLMENT\ENR_BASIS\G\', NULL, 'Geography: An assertion of complete data capture between the start and end dates based upon geographic characteristics, such as regional isolation', '@', '2001-01-01 00:00:00', '2001-01-01 00:00:00', '2001-01-01 00:00:00', 'PCORNET_CDM', NULL, NULL, '\PCORI\ENROLLMENT\ENR_BASIS\', 'G', 'ENR_BASIS:G');
INSERT INTO pcornet_enroll VALUES (3, '\PCORI\ENROLLMENT\ENR_BASIS\E\', 'Encounter-based', 'N', 'LA ', NULL, 'ENR_BASIS:E', NULL, 'PATIENT_NUM', 'VISIT_DIMENSION', 'start_date', 'N', 'IS NOT', ' NULL', NULL, 'Encounter-based: The start and stop dates are populated from the earliest- observed encounter and latest-observed encounter. Note: In i2b2, this is now automatically computed. Drag the item to the query window and set date constraints.', '@', '2014-06-04 00:00:00', '2014-06-04 00:00:00', '2014-06-04 00:00:00', 'PCORNET_CDM', NULL, NULL, '\PCORI\ENROLLMENT\ENR_BASIS\', 'E', 'ENR_BASIS:E');
INSERT INTO pcornet_enroll VALUES (2, '\PCORI\ENROLLMENT\VERSION\', 'zz Version 3.1', 'N', 'LI ', NULL, NULL, NULL, 'concept_cd', 'CONCEPT_DIMENSION', 'concept_path', 'T', 'LIKE', '\PCORI\ENROLLMENT\VERSION\', NULL, 'Version 3.1; see count value for total rows', '@', '2014-08-18 00:00:00', '2014-08-18 00:00:00', '2014-08-18 00:00:00', 'PCORNET_CDM', NULL, NULL, '\PCORI\ENROLLMENT\', 'VERSION', NULL);
INSERT INTO pcornet_enroll VALUES (3, '\PCORI\ENROLLMENT\ENR_BASIS\A\', 'Algorithmic', 'N', 'LI ', NULL, 'ENR_BASIS:A', NULL, 'PATIENT_NUM', 'OBSERVATION_FACT', 'start_date', 'N', 'IS NOT', ' NULL', NULL, 'Algorithmic: An assertion of complete data capture between the start and end dates, based on a locally developed or applied algorithm, often using multiple criteria', '@', '2001-01-01 00:00:00', '2001-01-01 00:00:00', '2001-01-01 00:00:00', 'PCORNET_CDM', NULL, NULL, '\PCORI\ENROLLMENT\ENR_BASIS\', 'A', 'ENR_BASIS:A');
INSERT INTO pcornet_enroll VALUES (3, '\PCORI\ENROLLMENT\ENR_BASIS\D\', 'Outpatient prescription drug coverage (v3.1)', 'N', 'LIE', NULL, 'ENR_BASIS:D', NULL, 'PATIENT_NUM', 'OBSERVATION_FACT', '1', 'N', '=', '0', 'CDMv3.1', 'Outpatient prescription drug coverage: The start and stop dates are based on enrollment where the health plan has any responsibility for covering outpatient prescription drugs for the member during this enrollment period (i.e., if you expect to observe outpatient pharmacy dispensings for this member during this enrollment period). (New value set item added in v3.1.)', '@', '2001-01-01 00:00:00', '2001-01-01 00:00:00', '2001-01-01 00:00:00', 'PCORNET_CDMv3.1', NULL, NULL, '\PCORI\ENROLLMENT\ENR_BASIS\', 'D', 'D');


--
-- PostgreSQL database dump complete
--

